{
    "Animated": true,
    "Duration": 2,
    "Message": "$(L,Action_Entity_Updated)",
    "Icon": "",
    "IsIconHidden": false,
    "NumberOfLines": 2,
    "OnSuccess": "/ReembolsoApp/Actions/CloseModalPage_Complete.action",
    "_Type": "Action.Type.ToastMessage"
}